# Generated by Django 2.2.6 on 2021-01-07 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
